yml
remote_theme: just-the-docs/just-the-docs
title: Disain erivajadustega lastele
description: Juhendite kogumik disaineritele ja arendajatele
sass:
  style: compressed

just_the_docs:
  custom_css:
    - assets/css/custom.css
